name: Expo CI CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Build-for-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "9.0.4" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: expo/expo-github-action@v7
        id: android
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install deps
        run: yarn install
      - name: Build Android APK Bundle
        run: expo build:android
  build-for-IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "9.0.4" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: sinoru/actions-setup-xcode@v1.1.2
        with:
          xcode-version: "11.2.1" # Exact version of a Xcode version to use
          apple-id: ${{ secrets.EXPO_APPLE_ID }} # Apple ID to download from Apple Developer when Xcode not available in local
          apple-id-password: ${{ secrets.EXPO_APPLE_PASSWORD }}
      - uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install deps
        run: yarn install
      - name: Build iOS app
        run: expo build:ios
        id: build_ios
        env:
          EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
          EXPO_APPLE_ID_PASSWORD: ${{secrets.EXPO_APPLE_PASSWORD}}
  send-bundle-via-email:
    # TODO  add build-for-IOS
    needs: [Build-for-android]
    runs-on: macos-latest
    steps:
      - uses: dawidd6/action-send-mail@v3.6.1
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: moataz@wuilt.com
          # Required sender full name (address can be skipped):
          from: Moataz Mohammady # <moataz@wuilt.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully! ${{ steps.android.outputs.value  }}
          # Optional HTML body read from file:
          html_body: ${{ steps.android.outputs.value  }}
          # Optional carbon copy recipients:
          cc: moataz@wuilt.com
          # # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # # Optional recipient of the email response:
          # reply_to: luke@example.com
          # # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # # Optional unsigned/invalid certificates allowance:
          # ignore_cert: true
          # # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
          # # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
